name: run-tests

on:
    push:
      branches:
        - master
    pull_request:
      branches:
        - master

jobs:
    test:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                php: [7.4, 7.3, 7.2, 7.1]
                # dependency-version: [prefer-lowest, prefer-stable]
                os: [ubuntu-latest]

        name: PHP${{ matrix.php }} - ${{ matrix.os }}

        services:
            mysql:
                image: mysql
                env:
                    MYSQL_ALLOW_EMPTY_PASSWORD: yes
                    MYSQL_DATABASE: phpauthtest
                ports:
                    - 3306
                options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
        
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  extensions: pdo, sqlite, pdo_sqlite, mysql, mysqli, pdo_mysql
                  coverage: none

            - name: Execute tests
              run: vendor/bin/phpunit
              env:
                  DB_PORT: ${{ job.services.mysql.ports[3306] }}